console.log("hello");
console.log("hello");
try{
    console.log(a);
} catch(err){
    console("error has been occure");
    console.log(err);
}

console.log("hello2");
console.log("hello2");